AWSTemplateFormatVersion: "2010-09-09"
Description: 'AWS CloudFormation Template: Create an Amazon EC2 instance with specified AMI ID, key pair, and VPC ID.'

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: ayatakey
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
    ConstraintDescription: must be a valid EC2 instance type.

  AMIId:
    Description: The AMI ID for the EC2 instance
    Type: String
    Default: ami-04b70fa74e45c3917

  VpcId:
    Description: The VPC ID where the instance will be launched
    Type: AWS::EC2::VPC::Id
    Default: vpc-0981608c1f7a67fef

  SubnetId:
    Description: The Subnet ID within the VPC
    Type: AWS::EC2::Subnet::Id
    Default: subnet-053d892402369d0f1

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: !Ref KeyName
      ImageId: !Ref AMIId
      Tags:
        - Key: Name
          Value: AyataCustomerMigration

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref EC2Instance

  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt EC2Instance.AvailabilityZone

  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt EC2Instance.PublicDnsName

  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
